### ISSUE TITLE
Dockerize Application

### ISSUE THREAD

**Issue by TannerBarcelos** [bradtraversy/mern-tutorial#7]
Dockerize application so it is easy to run cross-platform as well as deploy. Keeping the theme of modern development going, this is a great improvement to make. I can do this if you'd like in a PR!

**Comment by vikalp-tomer** [comment]
Hey, plz can you help me with dockerizing this application. I have interviews in upcoming weeks. If this app can be dockerized then it would be good for my resume.

**Comment by ghost** [comment]
Hi @vikalp-tomer 

this video will teach you how to dockerize the app
https://youtu.be/QePBbG5MoKk

good luck on your interview

**Comment by TannerBarcelos** [comment]
Closing as non priority
